steps:
  # Install dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']
    id: 'install'

  # Build the Vite project with environment variables
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_API_BASE_URL=https://nitipin-gateway-729492539702.us-central1.run.app'
    id: 'build'

  # Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud app deploy app.yaml --quiet'
    id: 'deploy'

options:
  logging: CLOUD_LOGGING_ONLY
